* IP quiz

IP arithmetic quizzes to keep your skills sharp.

Requires Python3.

*Usage:*

Run ~ip_quiz.py~ to start the program and select an option from the menu:

#+begin_example
1. Decimal integers (0-255) to bits
2. IPv4 address to network and broadcast addresses
3. IPv4 address to first and last host addresses

>
#+end_example

Quit the program by pressing ~Ctrl+D~ or ~Ctrl+C~.

** 1. Decimal integers (0-255) to bits

A random number from 0 to 255 is printed.  In the line below, enter the equivalent 8-bit value and press enter.  The correct 8-bit value is shown, and a new number is printed.

*Example:*

#+begin_example
245
11110101   <--- entered by user
11110101   <--- correct answer

170
10100110
10101010

30
00011110
00011110
#+end_example

** 2. IPv4 address to network and broadcast addresses

A random IP address in CIDR notation is printed.  In the following two lines, enter the network address and the broadcast address associated with the provided IP address.  The correct network and broadcasts addresses are shown, and a new random IP address is printed.  A dividing line is printed between quiz questions for clarity.

Randomly generated addresses include the theoretical maximum range of ~0.0.0.0~ to ~255.255.255.255~, and prefix lengths from ~0~ to ~32~.

*Example:*

#+begin_example
202.86.154.239/17
202.86.128.0       <--- network address entered by user
202.86.255.255     <--- broadcast address entered by user
202.86.128.0       <--- correct network address
202.86.255.255     <--- correct broadcast address

------------

104.214.58.141/4
96.0.0.0
112.255.255.255
96.0.0.0
111.255.255.255
#+end_example

** 3. IPv4 address to first and last host addresses

This quiz works the same as the previous one, except that it shows the first and last hosts addresses instead of the network and broadcast addresses.

*Example:*

#+begin_example
76.175.12.163/2
64.0.0.1
127.255.255.254
64.0.0.1
127.255.255.254

------------

238.176.39.31/26
238.176.39.1
238.176.39.63
238.176.39.1
238.176.39.62
#+end_example
